### ISSUE TITLE
tests/base_scraper/test_base_scraper.py::test_authentication failed

### ISSUE THREAD

**Issue by venkateshpitta** [mozilla/mozdownload#492]
The failure error message is,

> E           ConnectionError: HTTPConnectionPool(host='mozqa.com', port=80): Max retries exceeded with url: /data/mozqa.com/http_auth/basic/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd6f7a6ba50>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by whimboo** [comment]
Thank you for filing the issue! The problem here is that we shutdown mozqa.com (cc @fox2mike-mozilla-owner), and won't be able to continue to use this remote address to verify basic authentication. 

As such I would suggest we do it similarly as for Marionette and register a custom handler for wptserve which can handle that. You can mostly copy and paste what we have here:

https://dxr.mozilla.org/mozilla-central/rev/3205543f957cd2a6905486d73aa897535fdd9825/testing/marionette/harness/marionette_harness/runner/httpd.py#36
https://dxr.mozilla.org/mozilla-central/rev/3205543f957cd2a6905486d73aa897535fdd9825/testing/marionette/harness/marionette_harness/runner/httpd.py#105

That way we can use `http://localhost:8080/http_auth` which also removes the network requirement for this test.

@venkateshpitta would you like to work on it?

**Comment by venkateshpitta** [comment]
@whimboo Yes, I will work on this.

**Comment by whimboo** [comment]
Great! Thank you.

**Comment by whimboo** [comment]
This test we should try to fix as soon as possible. @venkateshpitta if you don't have the time to work on it please let me know, and I will update it.

**Comment by whimboo** [comment]
@ranjanp75 would like to try this issue. So given that you are new I would suggest that you first read the Readme of this repository and get the tests running. Once you know how that works we can continue.

**Comment by kaushiksk** [comment]
@whimboo kindly review the pr
